### ISSUE TITLE
module javafx.graphics does not "opens javafx.stage" to module com.pixelduke.fxthemes

### ISSUE THREAD

**Issue by GandalfTheWhite80** [dukke/FXThemes#1]
Trying to use your FXTemes 1.0.0 with java21/javafx 21 I'm running into the following stacktrace:

```
java.lang.reflect.InaccessibleObjectException: Unable to make com.sun.javafx.tk.TKStage javafx.stage.Window.getPeer() accessible: module javafx.graphics does not "opens javafx.stage" to module com.pixelduke.fxthemes
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:203)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:197)
	at com.pixelduke.fxthemes@1.0.0/com.pixelduke.window.WindowUtils.getNativeHandleOfStage(WindowUtils.java:13)
	at com.pixelduke.fxthemes@1.0.0/com.pixelduke.window.Win11ThemeWindowManager.setDarkModeForWindowFrame(Win11ThemeWindowManager.java:22)

---

java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.javafx.tk.quantum.WindowStage.getRawHandle() accessible: module javafx.graphics does not "exports com.sun.javafx.tk.quantum" to module com.pixelduke.fxthemes
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:203)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:197)
	at com.pixelduke.fxthemes@1.0.0/com.pixelduke.window.WindowUtils.getNativeHandleOfStage(WindowUtils.java:16)
	at com.pixelduke.fxthemes@1.0.0/com.pixelduke.window.Win11ThemeWindowManager.setDarkModeForWindowFrame(Win11ThemeWindowManager.java:22)	
```

My module-info:
```
    requires com.pixelduke.fxthemes;

    exports de.sph.discogs.main.gui to javafx.graphics;
```

The package "de.sph.discogs.main.gui " contains my gui/stages. But it seems that java is not complainig about my package :-(.

Java src:
```java
final ThemeWindowManager twm= ThemeWindowManagerFactory.create();
twm.setDarkModeForWindowFrame(stage, true);
```

**Comment by GandalfTheWhite80** [comment]
PS Must I run any application using FXThemes with "--add-opens javafx.graphics/javafx.stage=com.pixelduke.fxthemes --add-exports javafx.graphics/com.sun.javafx.tk.quantum=com.pixelduke.fxthemes"?

**Comment by dukke** [comment]
Yes, that's it.
You need to add the same things that are added in the samples... check the sample apps.

Thanks!
